### ISSUE TITLE
SlimPruner使用

### ISSUE THREAD

**Issue by GeneralJing** [Sanster/pytorch-network-slimming#3]
今天对gen_schema.py进行了改写生成了需要的json文件，在看train代码的时候，前面使用pytorch lightning对模型进行一层封装，SlimPruner初始化的时候传入的参数是LitModel类型的实例，如果原始网络的代码是pytorch的，也要进行类似的操作吗？
restored_model = LitModel.load_from_checkpoint(last_model_path, args=args)

pruner = SlimPruner(restored_model, args.prune_schema)
pruning_result = pruner.run(args.prune_ratio)
在readme里面没有提到这个地方，所以有点疑问。
另外就是看pytorch lightning这块代码，因为对pytorch lightning不熟悉，这个在回调函数中设置的路径，会在训练的时候进行模型的保存吗？感觉有点不习惯。

**Comment by Sanster** [comment]
1. 不需要，SlimPruner 和 pytorch lightning 没有关系
 1. 是的，训练过程中 ModelCheckpoint 这个 Callback 类负责保存模型

**Comment by GeneralJing** [comment]
好的，多谢，正在进行稀疏训练。今天有时间写下剪枝这块调用及微调的代码，多谢大佬。
