### ISSUE TITLE
KeyError: 'encoder.level1.conv'

### ISSUE THREAD

**Issue by GeneralJing** [Sanster/pytorch-network-slimming#4]
Traceback (most recent call last):
  File "prune.py", line 126, in <module>
    pruner = SlimPruner(model, "/home/jing/model/schema/model.json")
  File "/home/jing/pytorch-network-slimming/src/pns/pns.py", line 187, in __init__
    modules[name]["name"],
KeyError: 'encoder.level1.conv'
使用生成的json文件进行SlimPruner初始化的时候报错了，这个地方使用有啥注意的地方吗？
另外，
pruning_result = pruner.run(args.prune_ratio)
和pruner.pruned_model的区别是什么呢

**Comment by Sanster** [comment]
把你的 model state_dict 的 key 打一下

**Comment by GeneralJing** [comment]
model.state_dict: <bound method Module.state_dict of SBNet_aux(
  (encoder): SBNet_Encoder(
    (level1): CBR(
      (conv): Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn): BatchNorm2d(16, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
      (act): ReLU(inplace=True)
    )
    (level2_0): SEseparableCBR(
      (conv): Sequential(
        (0): Conv2d(16, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=16, bias=False)
        (1): Conv2d(16, 12, kernel_size=(1, 1), stride=(1, 1), bias=False)
      )
      (bn): BatchNorm2d(12, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
      (act): ReLU(inplace=True)
    )
    (level3_0): SEseparableCBR(
      (conv): Sequential(
        (0): Conv2d(12, 12, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=12, bias=False)
        (1): Conv2d(12, 24, kernel_size=(1, 1), stride=(1, 1), bias=False)
      )
      (bn): BatchNorm2d(24, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
      (act): ReLU(inplace=True)
    )
    (level3): ModuleList(
      (0): SBmodule(
        (c1): C(
          (conv): Conv2d(24, 30, kernel_size=(1, 1), stride=(1, 1), groups=2, bias=False)
        )
        (d1): SBblock(
          (vertical): Conv2d(30, 30, kernel_size=(3, 1), stride=(1, 1), padding=(1, 0), groups=30, bias=False)
          (B_v): BatchNorm2d(30, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (horizontal): Conv2d(30, 30, kernel_size=(1, 3), stride=(1, 1), padding=(0, 1), groups=30, bias=False)
          (B_h): BatchNorm2d(30, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(30, 30, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(30, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (d2): SBblock(
          (vertical): Conv2d(30, 30, kernel_size=(5, 1), stride=(1, 1), padding=(2, 0), groups=30, bias=False)
          (B_v): BatchNorm2d(30, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (horizontal): Conv2d(30, 30, kernel_size=(1, 5), stride=(1, 1), padding=(0, 2), groups=30, bias=False)
          (B_h): BatchNorm2d(30, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(30, 30, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(30, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (BR): BR(
          (bn): BatchNorm2d(60, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act): ReLU(inplace=True)
        )
      )
      (1): SBmodule(
        (c1): C(
          (conv): Conv2d(60, 30, kernel_size=(1, 1), stride=(1, 1), groups=2, bias=False)
        )
        (d1): SBblock(
          (conv): Sequential(
            (0): Conv2d(30, 30, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=30, bias=False)
            (1): BatchNorm2d(30, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          )
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(30, 30, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(30, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (d2): SBblock(
          (vertical): Conv2d(30, 30, kernel_size=(3, 1), stride=(1, 1), padding=(1, 0), groups=30, bias=False)
          (B_v): BatchNorm2d(30, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (horizontal): Conv2d(30, 30, kernel_size=(1, 3), stride=(1, 1), padding=(0, 1), groups=30, bias=False)
          (B_h): BatchNorm2d(30, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(30, 30, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(30, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (BR): BR(
          (bn): BatchNorm2d(60, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act): ReLU(inplace=True)
        )
      )
      (2): SBmodule(
        (c1): C(
          (conv): Conv2d(60, 30, kernel_size=(1, 1), stride=(1, 1), groups=2, bias=False)
        )
        (d1): SBblock(
          (conv): Sequential(
            (0): Conv2d(30, 30, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=30, bias=False)
            (1): BatchNorm2d(30, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          )
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(30, 30, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(30, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (d2): SBblock(
          (vertical): Conv2d(30, 30, kernel_size=(3, 1), stride=(1, 1), padding=(1, 0), groups=30, bias=False)
          (B_v): BatchNorm2d(30, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (horizontal): Conv2d(30, 30, kernel_size=(1, 3), stride=(1, 1), padding=(0, 1), groups=30, bias=False)
          (B_h): BatchNorm2d(30, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(30, 30, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(30, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (BR): BR(
          (bn): BatchNorm2d(60, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act): ReLU(inplace=True)
        )
      )
    )
    (BR3): BR(
      (bn): BatchNorm2d(84, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
      (act): ReLU(inplace=True)
    )
    (level4_0): SEseparableCBR(
      (conv): Sequential(
        (0): Conv2d(84, 84, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=84, bias=False)
        (1): Conv2d(84, 60, kernel_size=(1, 1), stride=(1, 1), bias=False)
      )
      (bn): BatchNorm2d(60, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
      (act): ReLU(inplace=True)
    )
    (level4): ModuleList(
      (0): SBmodule(
        (c1): C(
          (conv): Conv2d(60, 42, kernel_size=(1, 1), stride=(1, 1), groups=2, bias=False)
        )
        (d1): SBblock(
          (vertical): Conv2d(42, 42, kernel_size=(3, 1), stride=(1, 1), padding=(1, 0), groups=42, bias=False)
          (B_v): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (horizontal): Conv2d(42, 42, kernel_size=(1, 3), stride=(1, 1), padding=(0, 1), groups=42, bias=False)
          (B_h): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(42, 42, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (d2): SBblock(
          (vertical): Conv2d(42, 42, kernel_size=(5, 1), stride=(1, 1), padding=(2, 0), groups=42, bias=False)
          (B_v): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (horizontal): Conv2d(42, 42, kernel_size=(1, 5), stride=(1, 1), padding=(0, 2), groups=42, bias=False)
          (B_h): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(42, 42, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (BR): BR(
          (bn): BatchNorm2d(84, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act): ReLU(inplace=True)
        )
      )
      (1): SBmodule(
        (c1): C(
          (conv): Conv2d(84, 42, kernel_size=(1, 1), stride=(1, 1), groups=2, bias=False)
        )
        (d1): SBblock(
          (conv): Sequential(
            (0): Conv2d(42, 42, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=42, bias=False)
            (1): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          )
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(42, 42, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (d2): SBblock(
          (vertical): Conv2d(42, 42, kernel_size=(3, 1), stride=(1, 1), padding=(1, 0), groups=42, bias=False)
          (B_v): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (horizontal): Conv2d(42, 42, kernel_size=(1, 3), stride=(1, 1), padding=(0, 1), groups=42, bias=False)
          (B_h): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(42, 42, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (BR): BR(
          (bn): BatchNorm2d(84, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act): ReLU(inplace=True)
        )
      )
      (2): SBmodule(
        (c1): C(
          (conv): Conv2d(84, 42, kernel_size=(1, 1), stride=(1, 1), groups=2, bias=False)
        )
        (d1): SBblock(
          (vertical): Conv2d(42, 42, kernel_size=(5, 1), stride=(1, 1), padding=(2, 0), groups=42, bias=False)
          (B_v): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (horizontal): Conv2d(42, 42, kernel_size=(1, 5), stride=(1, 1), padding=(0, 2), groups=42, bias=False)
          (B_h): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(42, 42, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (d2): SBblock(
          (down_res): AvgPool2d(kernel_size=4, stride=4, padding=0)
          (up_res): UpsamplingBilinear2d(scale_factor=4.0, mode=bilinear)
          (vertical): Conv2d(42, 42, kernel_size=(5, 1), stride=(1, 1), padding=(2, 0), groups=42, bias=False)
          (B_v): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (horizontal): Conv2d(42, 42, kernel_size=(1, 5), stride=(1, 1), padding=(0, 2), groups=42, bias=False)
          (B_h): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(42, 42, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (BR): BR(
          (bn): BatchNorm2d(84, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act): ReLU(inplace=True)
        )
      )
      (3): SBmodule(
        (c1): C(
          (conv): Conv2d(84, 42, kernel_size=(1, 1), stride=(1, 1), groups=2, bias=False)
        )
        (d1): SBblock(
          (down_res): AvgPool2d(kernel_size=2, stride=2, padding=0)
          (up_res): UpsamplingBilinear2d(scale_factor=2.0, mode=bilinear)
          (vertical): Conv2d(42, 42, kernel_size=(3, 1), stride=(1, 1), padding=(1, 0), groups=42, bias=False)
          (B_v): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (horizontal): Conv2d(42, 42, kernel_size=(1, 3), stride=(1, 1), padding=(0, 1), groups=42, bias=False)
          (B_h): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(42, 42, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (d2): SBblock(
          (down_res): AvgPool2d(kernel_size=4, stride=4, padding=0)
          (up_res): UpsamplingBilinear2d(scale_factor=4.0, mode=bilinear)
          (vertical): Conv2d(42, 42, kernel_size=(5, 1), stride=(1, 1), padding=(2, 0), groups=42, bias=False)
          (B_v): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (horizontal): Conv2d(42, 42, kernel_size=(1, 5), stride=(1, 1), padding=(0, 2), groups=42, bias=False)
          (B_h): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(42, 42, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (BR): BR(
          (bn): BatchNorm2d(84, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act): ReLU(inplace=True)
        )
      )
      (4): SBmodule(
        (c1): C(
          (conv): Conv2d(84, 42, kernel_size=(1, 1), stride=(1, 1), groups=2, bias=False)
        )
        (d1): SBblock(
          (vertical): Conv2d(42, 42, kernel_size=(3, 1), stride=(1, 1), padding=(1, 0), groups=42, bias=False)
          (B_v): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (horizontal): Conv2d(42, 42, kernel_size=(1, 3), stride=(1, 1), padding=(0, 1), groups=42, bias=False)
          (B_h): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(42, 42, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (d2): SBblock(
          (vertical): Conv2d(42, 42, kernel_size=(5, 1), stride=(1, 1), padding=(2, 0), groups=42, bias=False)
          (B_v): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (horizontal): Conv2d(42, 42, kernel_size=(1, 5), stride=(1, 1), padding=(0, 2), groups=42, bias=False)
          (B_h): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(42, 42, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(42, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (BR): BR(
          (bn): BatchNorm2d(84, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act): ReLU(inplace=True)
        )
      )
      (5): SBmodule(
        (c1): C(
          (conv): Conv2d(84, 54, kernel_size=(1, 1), stride=(1, 1), groups=2, bias=False)
        )
        (d1): SBblock(
          (vertical): Conv2d(54, 54, kernel_size=(3, 1), stride=(1, 1), padding=(1, 0), groups=54, bias=False)
          (B_v): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (horizontal): Conv2d(54, 54, kernel_size=(1, 3), stride=(1, 1), padding=(0, 1), groups=54, bias=False)
          (B_h): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(54, 54, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (d2): SBblock(
          (vertical): Conv2d(54, 54, kernel_size=(5, 1), stride=(1, 1), padding=(2, 0), groups=54, bias=False)
          (B_v): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (horizontal): Conv2d(54, 54, kernel_size=(1, 5), stride=(1, 1), padding=(0, 2), groups=54, bias=False)
          (B_h): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(54, 54, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (BR): BR(
          (bn): BatchNorm2d(108, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act): ReLU(inplace=True)
        )
      )
      (6): SBmodule(
        (c1): C(
          (conv): Conv2d(108, 54, kernel_size=(1, 1), stride=(1, 1), groups=2, bias=False)
        )
        (d1): SBblock(
          (conv): Sequential(
            (0): Conv2d(54, 54, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=54, bias=False)
            (1): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          )
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(54, 54, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (d2): SBblock(
          (vertical): Conv2d(54, 54, kernel_size=(3, 1), stride=(1, 1), padding=(1, 0), groups=54, bias=False)
          (B_v): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (horizontal): Conv2d(54, 54, kernel_size=(1, 3), stride=(1, 1), padding=(0, 1), groups=54, bias=False)
          (B_h): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(54, 54, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (BR): BR(
          (bn): BatchNorm2d(108, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act): ReLU(inplace=True)
        )
      )
      (7): SBmodule(
        (c1): C(
          (conv): Conv2d(108, 54, kernel_size=(1, 1), stride=(1, 1), groups=2, bias=False)
        )
        (d1): SBblock(
          (vertical): Conv2d(54, 54, kernel_size=(5, 1), stride=(1, 1), padding=(2, 0), groups=54, bias=False)
          (B_v): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (horizontal): Conv2d(54, 54, kernel_size=(1, 5), stride=(1, 1), padding=(0, 2), groups=54, bias=False)
          (B_h): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(54, 54, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (d2): SBblock(
          (down_res): AvgPool2d(kernel_size=4, stride=4, padding=0)
          (up_res): UpsamplingBilinear2d(scale_factor=4.0, mode=bilinear)
          (vertical): Conv2d(54, 54, kernel_size=(5, 1), stride=(1, 1), padding=(2, 0), groups=54, bias=False)
          (B_v): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (horizontal): Conv2d(54, 54, kernel_size=(1, 5), stride=(1, 1), padding=(0, 2), groups=54, bias=False)
          (B_h): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(54, 54, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (BR): BR(
          (bn): BatchNorm2d(108, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act): ReLU(inplace=True)
        )
      )
      (8): SBmodule(
        (c1): C(
          (conv): Conv2d(108, 54, kernel_size=(1, 1), stride=(1, 1), groups=2, bias=False)
        )
        (d1): SBblock(
          (down_res): AvgPool2d(kernel_size=2, stride=2, padding=0)
          (up_res): UpsamplingBilinear2d(scale_factor=2.0, mode=bilinear)
          (vertical): Conv2d(54, 54, kernel_size=(3, 1), stride=(1, 1), padding=(1, 0), groups=54, bias=False)
          (B_v): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (horizontal): Conv2d(54, 54, kernel_size=(1, 3), stride=(1, 1), padding=(0, 1), groups=54, bias=False)
          (B_h): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(54, 54, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (d2): SBblock(
          (down_res): AvgPool2d(kernel_size=4, stride=4, padding=0)
          (up_res): UpsamplingBilinear2d(scale_factor=4.0, mode=bilinear)
          (vertical): Conv2d(54, 54, kernel_size=(5, 1), stride=(1, 1), padding=(2, 0), groups=54, bias=False)
          (B_v): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (horizontal): Conv2d(54, 54, kernel_size=(1, 5), stride=(1, 1), padding=(0, 2), groups=54, bias=False)
          (B_h): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(54, 54, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (BR): BR(
          (bn): BatchNorm2d(108, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act): ReLU(inplace=True)
        )
      )
      (9): SBmodule(
        (c1): C(
          (conv): Conv2d(108, 54, kernel_size=(1, 1), stride=(1, 1), groups=2, bias=False)
        )
        (d1): SBblock(
          (conv): Sequential(
            (0): Conv2d(54, 54, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=54, bias=False)
            (1): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          )
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(54, 54, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (d2): SBblock(
          (down_res): AvgPool2d(kernel_size=2, stride=2, padding=0)
          (up_res): UpsamplingBilinear2d(scale_factor=2.0, mode=bilinear)
          (vertical): Conv2d(54, 54, kernel_size=(5, 1), stride=(1, 1), padding=(2, 0), groups=54, bias=False)
          (B_v): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (horizontal): Conv2d(54, 54, kernel_size=(1, 5), stride=(1, 1), padding=(0, 2), groups=54, bias=False)
          (B_h): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act_conv1x1): Sequential(
            (0): ReLU(inplace=True)
            (1): Conv2d(54, 54, kernel_size=(1, 1), stride=(1, 1), bias=False)
          )
          (bn): BatchNorm2d(54, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (BR): BR(
          (bn): BatchNorm2d(108, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act): ReLU(inplace=True)
        )
      )
    )
    (BR4): BR(
      (bn): BatchNorm2d(168, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
      (act): ReLU(inplace=True)
    )
    (classifier): C(
      (conv): Conv2d(168, 12, kernel_size=(1, 1), stride=(1, 1), bias=False)
    )
  )
  (bn_4): BatchNorm2d(12, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
  (level3_C): CBR(
    (conv): Conv2d(60, 12, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (bn): BatchNorm2d(12, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
    (act): ReLU(inplace=True)
  )
  (bn_3): BatchNorm2d(12, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
  (output): UpsamplingBilinear2d(scale_factor=2.0, mode=bilinear)
  (classifier): DepthSepConv2d(
    (depth_conv): Conv2d(12, 12, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=12)
    (point_conv): Conv2d(12, 12, kernel_size=(1, 1), stride=(1, 1))
  )
)

**Comment by Sanster** [comment]
`model.json`里面里面是不是有个 "prefix" 的值有有设么，gen_schema.py 默认会加一个 "model." prefix，去掉试试，还是不行的话把 model.json 也贴上来吧

**Comment by GeneralJing** [comment]
我把prefix的值设为空后，初始化的地方应该是可以了，但是下面会报错，如下：
Traceback (most recent call last):
  File "prune.py", line 128, in <module>
    pruning_result = pruner.run(0.8)
  File "/home/jing/pytorch-network-slimming/src/pns/pns.py", line 245, in run
    self.bn2d_modules[conv2d.next_bn_name] if conv2d.next_bn_name else None,
  File "/home/jing/pytorch-network-slimming/src/pns/pns.py", line 45, in prune
    next_bn.keep_idxes if next_bn else None,
  File "/home/jing/pytorch-network-slimming/src/pns/functional.py", line 60, in prune_conv2d
    assert len(in_keep_idxes) <= module.weight.shape[1]
AssertionError
不知道这个是跟模型有关系吗？

**Comment by Sanster** [comment]
有关系，不支持分组卷积。

notes for me：理论上是可以支持的，Conv -> BN -> GroupConv，如果 BN 剪枝了，保留的通道数必须被 GroupConv 的 group 整除，GroupConv weigths 的第二维不剪枝。BN 层可以根据 weights ，取被剪掉的channel中最大的 weight 来补齐 keep_indexes，主要修改点应该是在 BN2dWrapper 里面，但是 BN2dWrapper 不知道下一层是不是 GroupConv，这个数据怎么传递？

**Comment by GeneralJing** [comment]
这个可不可以这样规避？就是过滤分组卷积前面的BN剪枝，这样遇到分组卷积提供一种折中方式，至少不崩溃。
